Use Mantenedor;
Go
CREATE TABLE DBO.CLIENTE(
		CLIENTE_AUTOID [numeric](18,0) IDENTITY(1,1) PRIMARY KEY,
		CLIENTE_DESCRIPCION VARCHAR(225) NULL,
		CLIENTE_RUT VARCHAR(15) NULL,
		CLIENTE_CODIGO_CONTABLE VARCHAR(10) NULL,
		CLIENTE_FACTURABLE INT NULL,
		CLIENTE_LOGOA VARCHAR(MAX) NULL,
		CLIENTE_ESTADO [BIT] NOT NULL,
		CLIENTE_LOGOB VARCHAR(MAX) NULL,
		CLIENTE_NOMBRE_FANTASIA VARCHAR(225) NULL,
);


INSERT INTO CLIENTE (CLIENTE_DESCRIPCION, CLIENTE_RUT, CLIENTE_CODIGO_CONTABLE, CLIENTE_FACTURABLE, CLIENTE_LOGOA, CLIENTE_ESTADO, CLIENTE_LOGOB, CLIENTE_NOMBRE_FANTASIA) VALUES

(N'MERCHANDISING',                         N'77128770M', 43, 1, 'TEST', 1, 'TEST', 'Merchandiging'),
(N'TRENDY S.A.',                          N'781094706', 68, 1, 'TEST', 1, 'TEST', 'Trendy'),
(N'COLUN LTDA.',                          N'810941006', 64, 1, 'TEST', 1, 'TEST', 'Colun'),
(N'SONDA S.A.',                           N'836281004',  8, 1, 'TEST', 1, 'TEST', 'Sonda'),
(N'FARMACIAS CRUZ VERDE S.A.',            N'898072002', 77, 1, 'TEST', 1, 'TEST', 'Farmacias Cruz Verde'),
(N'NESTLÉ CHILE S.A.',                    N'907030008', 70, 1, 'TEST', 1, 'TEST', 'Nestle'),
(N'EMBOTELLADORA ANDINA S.A.',            N'911440008', 67, 1, 'TEST', 1, 'TEST', 'Andina'),
(N'SOPROLE S.A.',                         N'914920000',  1, 1, 'TEST', 1, 'TEST', 'Soprole'),
(N'LABORATORIO BALLERINA LTDA.',          N'924050004',  3, 1, 'TEST', 1, 'TEST', 'Laboratorio Ballerina'),
(N'S.C. JOHNSON & SON CHILE LIMITADA',    N'932400006', 76, 1, 'TEST', 1, 'TEST', 'Johnson');