USE Mantenedor;
GO
DROP PROCEDURE IF EXISTS MANT_CUENTA_DELETE;
GO

CREATE PROCEDURE MANT_CUENTA_DELETE
    @ID_CUENTA INT
AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM CLIENTE WHERE CLIENTE_AUTOID = @ID_CUENTA;
    DELETE FROM CUENTA WHERE ID_CUENTA = @ID_CUENTA;
END;
GO

SELECT * FROM CLIENTE

