Use Mantenedor;
Go
Create or Alter procedure Mant_Ciente_Traer_Ddl
AS
BEGIN
SELECT
	CLIENTE_AUTOID,
	CLIENTE_DESCRIPCION
	FROM CLIENTE
	WHERE CLIENTE_ESTADO = '1'
	ORDER BY CLIENTE_DESCRIPCION;
	END
GO

Create or Alter procedure Mant_Empresa_Traer_Ddl
AS
BEGIN
SELECT 
	EMPRESA_AUTOID,
	EMPRESA_NOMBRE
	FROM EMPRESA
	WHERE EMPRESA_ESTADO = '1'
	ORDER BY EMPRESA_NOMBRE;
END
GO

Create or Alter procedure Mant_Comuna_Traer_Ddl
AS
BEGIN
SELECT 
	NRO_COMUNA,
	NOMBRE_COMUNA
	FROM COMUNA
	WHERE ESTADO_COMUNA = '1'
	ORDER BY NOMBRE_COMUNA;
END
GO

SELECT * FROM CLIENTE