USE Mantenedor;
GO
CREATE OR ALTER PROCEDURE MANT_CUENTA_TRAER
AS
BEGIN
    SELECT
        C.ID_CUENTA,
        C.CTA_NOMBRE,
        C.CTA_RUT,
        C.CTA_DIRECCION,
        C.CTA_COMUNA,
        C.CTA_ESTADO,
        C.CTA_MAIL,
        C.CTA_ENCARGADO,
        C.CTA_GEO_CONSUMERKEY,
        C.CTA_GEO_CONSUMERSECRET,
        C.CTA_PERIODO_CONTROL_ASISTENCIA,
        C.CLIENTE_AUTOID,
        COALESCE(C.CLIENTE_DESCRIPCION, CL.CLIENTE_DESCRIPCION) AS CLIENTE_DESCRIPCION,
        CL.CLIENTE_RUT,
        CL.CLIENTE_CODIGO_CONTABLE,
        CL.CLIENTE_NOMBRE_FANTASIA,
        CL.CLIENTE_DESCRIPCION,
        CL.CLIENTE_CODIGO_CONTABLE,
        CL.CLIENTE_FACTURABLE,
        CL.CLIENTE_LOGOA,
        CL.CLIENTE_LOGOB,
        CL.CLIENTE_NOMBRE_FANTASIA,
        C.EMPRESA_AUTOID,
        COALESCE(C.EMPRESA_NOMBRE, E.EMPRESA_NOMBRE) AS EMPRESA_NOMBRE, 
        E.EMPRESA_CODIGO,
        E.EMPRESA_CODIGO_CONTABLE,
        E.EMPRESA_TELEFONO,
        E.EMPRESA_RUT,
        E.EMPRESA_DIRECCION,
        E.EMPRESA_DIRECCION_FACTURACION
    FROM CUENTA C
    LEFT JOIN CLIENTE CL ON C.CLIENTE_AUTOID = CL.CLIENTE_AUTOID
    LEFT JOIN EMPRESA E ON C.EMPRESA_AUTOID = E.EMPRESA_AUTOID
    ORDER BY C.ID_CUENTA DESC;
END

SELECT * FROM CUENTA